version: '3.9'

services:
  php:
    build:
      context: docker/php-fpm/local
    volumes:
      - ./docker/php-fpm/local/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - /var/www/html/vendor
      - /var/www/html/var
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    volumes:
      - ./docker/mysql/local/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  nginx:
    build:
      context: docker/nginx/local
