version: '3.9'

services:
  php:
    restart: unless-stopped
    working_dir: /var/www/html
    tty: true
    build:
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${APP_PATH}:/var/www/html:rw

  mysql:
    image: mariadb:10.7.3
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"

  nginx:
    restart: unless-stopped
    tty: true
    build:
      args:
        SERVER_NAME: ${SERVER_NAME}
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${APP_PATH}:/var/www/html:rw
      - ${LOG_PATH}/nginx/:/var/log/nginx



