Employee:
    resource:
        path: ../src/Employee/Application/Controller/
        namespace: App\Employee\Application\Controller
    type: attribute


api_access_token:
    path: /api/access_token
    methods: ['POST']

api_refresh_token:
    path: /api/refresh_token
    methods: ['POST']

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
